language: php

os:
  - linux
  
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

script: php phpunit-5.7.phar -c ./build/phpunit.xml --coverage-text

before_install:
  - curl -O https://phar.phpunit.de/phpunit-5.7.phar;
  - chmod +x phpunit-5.7.phar
