language: php

os:
  - linux
  - osx

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

script: php phpunit.phar -c ./build/phpunit.xml --coverage-text

before_install:
  - wget https://phar.phpunit.de/phpunit.phar;
  - chmod +x phpunit.phar