#!/usr/bin/env php
<?php
/**
 * Spaceman is the command-line interface included with Advandz. It provides a number of helpful
 * commands that can assist you while you build your application.
 *
 * @package Advandz
 * @copyright Copyright (c) 2012-2017 CyanDark, Inc. All Rights Reserved.
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 * @author The Advandz Team <team@advandz.com>
 */

namespace Advandz;

/**
 * Refuse to run oil when called from php-cgi
 */
if (substr(php_sapi_name(), 0, 3) == 'cgi')  {
    die("The use of spaceman is not supported when running php-cgi. Spaceman needs php-cli to function!\n\n");
}

/**
 * Load the Advandz autoloader and boot the app
 */
include(dirname(__FILE__) . "/lib/init.php");

/**
 * Launch the command line interface
 */
Cli::init($_SERVER['argv']);