#!/usr/bin/env php
<?php
/**
 * Spaceman is the command-line interface included with Advandz. It provides a number of helpful
 * commands that can assist you while you build your application.
 *
 * @package Advandz
 * @copyright Copyright (c) 2016-2017 Advandz, LLC. All Rights Reserved.
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 * @author The Advandz Team <team@advandz.com>
 */

/**
 * Refuse to run spaceman when called from php-cgi
 */
if (substr(php_sapi_name(), 0, 3) == 'cgi') {
    die("The use of Spaceman is not supported when running php-cgi. Spaceman needs php-cli to function!\n");
}

/**
 * Load the Advandz autoloader and boot the app
 */
include(dirname(__FILE__) . "/lib/init.php");

/**
 * Launch the command line interface
 */
Spaceman::initialize($_SERVER['argv']);
